export const attributes={Intelecto:['Foco profundo','Pensamiento crítico','Memoria','Aprendizaje','Planificación'],Carisma:['Comunicación','Escucha activa','Presencia','Negociación','Liderazgo'],Rendimiento:['Disciplina','Consistencia','Gestión del tiempo','Resiliencia','Ejecución'],Físico:['Fuerza','Resistencia','Movilidad','Composición corporal','Recuperación']};
export const questions=Array.from({length:30},(_,i)=>({id:i+1,text:[...Object.values(attributes).flat(), 'Duermo con horarios regulares','Mantengo energía estable','Cumplo lo que planifico','Gestiono bien el estrés','Reviso mi progreso','Entreno con intención','Como de forma estructurada','Pido feedback','Termino lo que empiezo','Adapto mi plan'][i%30],attr:Object.keys(attributes)[i%4]}));
export const exercises=[
 {id:'squat',name:'Sentadilla goblet',target:'Piernas · fuerza',tech:'Pecho alto, rodillas acompañan la punta de los pies y profundidad controlada.',sets:3,reps:10,rest:75,img:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
 {id:'row',name:'Remo con mancuerna',target:'Espalda · postura',tech:'Columna neutra, codo hacia la cadera y pausa arriba.',sets:3,reps:12,rest:60,img:'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?auto=format&fit=crop&w=900&q=80'},
 {id:'press',name:'Press inclinado',target:'Pecho · empuje',tech:'Escápulas estables, antebrazos verticales y bajada lenta.',sets:3,reps:8,rest:90,img:'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=900&q=80'}];
export const meals=[
 {id:'breakfast',slot:'Desayuno',name:'Yogur proteico con avena y frutos rojos',kcal:480,p:35,c:58,f:12,img:'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=900&q=80',ingredients:'250 g yogur griego, 50 g avena, 100 g frutos rojos, 15 g nueces',steps:'Mezclá yogur y avena. Sumá fruta y terminá con nueces.'},
 {id:'lunch',slot:'Almuerzo',name:'Bowl de pollo, arroz y vegetales',kcal:690,p:52,c:78,f:18,img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',ingredients:'180 g pollo, 100 g arroz en crudo, brócoli, zanahoria, oliva',steps:'Cociná el arroz. Dorá el pollo. Salteá vegetales y armá el bowl.'},
 {id:'snack',slot:'Merienda',name:'Tostadas con huevo y palta',kcal:410,p:22,c:38,f:20,img:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',ingredients:'2 tostadas integrales, 2 huevos, 1/2 palta, tomate',steps:'Tostá el pan, cociná los huevos y montá con palta y tomate.'},
 {id:'dinner',slot:'Cena',name:'Salmón con batata y verdes',kcal:620,p:44,c:54,f:25,img:'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=900&q=80',ingredients:'180 g salmón, 250 g batata, hojas verdes, limón',steps:'Horneá la batata 30 min. Cociná el salmón 10–12 min y serví con verdes.'}];
export const academy=[
 {id:'discipline',title:'Disciplina sin fricción',skill:'Disciplina',lessons:[['Diseñá el entorno','La disciplina sostenible empieza reduciendo decisiones. Dejá visible lo importante, prepará la noche anterior y definí un inicio de dos minutos.'],['Regla del mínimo viable','En días difíciles, protegé la identidad con una versión pequeña del hábito. Consistencia antes que intensidad.'],['Revisión semanal','Medí adherencia, detectá fricción y cambiá una sola variable por semana.']]},
 {id:'focus',title:'Foco de combate',skill:'Foco profundo',lessons:[['Bloques de atención','Elegí una salida concreta, cerrá entradas y trabajá 25–50 minutos sin alternar.'],['Recuperar la atención','Cuando aparezca una distracción, anotala y volvé al siguiente gesto físico de la tarea.'],['Energía cognitiva','Ubicá el trabajo exigente en tu franja de mayor energía y agrupá lo administrativo.']]},
 {id:'communication',title:'Comunicación intencional',skill:'Comunicación',lessons:[['Escuchar antes de responder','Reflejando hechos, emoción y necesidad reducís malentendidos antes de proponer soluciones.'],['Mensajes claros','Contexto breve, pedido observable y fecha concreta. Evitá insinuaciones.'],['Conversaciones difíciles','Describí conducta e impacto sin atacar identidad; acordá el próximo paso.']]},
 {id:'physical',title:'Rendimiento físico',skill:'Recuperación',lessons:[['Sobrecarga progresiva','Progresá una variable por vez: repeticiones, carga, series o control técnico.'],['RPE útil','RPE 8 significa unas dos repeticiones en reserva. Registrarlo mejora decisiones futuras.'],['Recuperación activa','Sueño, proteína, pasos y manejo de fatiga sostienen más progreso que sesiones heroicas aisladas.']]}];
export const combatSkills=Array.from({length:28},(_,i)=>({id:i+1,name:['Corte umbral','Guardia espectral','Lectura táctica','Pulso de control'][i%4]+' '+(Math.floor(i/4)+1),type:['Ataque','Defensa','Táctica','Control'][i%4],power:8+(i%7)*2,unlocked:i<8}));
export const minigames=['Memoria de runas','Reflejo relámpago','Cálculo veloz','Foco sostenido','Tiro preciso','Decisión táctica','Secuencia sombra','Reacción dual','Patrón oculto','Pulso estable'];
